name: Build iOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Pobierz projekt
        uses: actions/checkout@v4

      - name: Sprawdź Xcode
        run: |
          xcode-select -p
          xcodebuild -version

      - name: Zbuduj aplikację iOS
        run: |
          xcodebuild \
            -project "RESUSCYTACJA_z_AED.xcodeproj" \
            -scheme "RESUSCYTACJA_z_AED" \
            -sdk iphonesimulator \
            -configuration Debug \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            build
